version: '3.7'

services:
  mini-api-node:
    container_name: mini-api-node
    build: ${MINI_API_PATH:-.}/docker/node
    image: nexus.wako057.net:18442/mini-api-node:1.0.0
    volumes:
      - ${MINI_API_PATH:-.}/:/var/nodejs/mini-api-node
    expose:
      - 8080
    labels:
      traefik.frontend.rule: "Host: mini-api.wako057.net"
      traefik.docker.network: "front"
      traefik.port: 8080
      traefik.frontend.entryPoints: http
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
      DATABASES_HOST: dev-pgsql-01.dev.wako057.net
      DATABASES_PORT: 5432
      DATABASES_USER: miniapi
      DATABASES_PASSWORD: miniapi
      DATABASES_DATABASE: miniapi
    networks:
      front:
        aliases:
          - mini-api.wako057.net
      back:
        aliases:
          - mini-api.back.wako057.net

  factory-api-node:
    container_name: factory-api-node
    build: ${MINI_API_PATH:-.}/docker/node-factory
    image: nexus.wako057.net:18442/factory-api-node:1.0.0
    volumes:
      - ${MINI_API_PATH:-.}/:/var/nodejs/factory-api-node
    expose:
      - 8080
    labels:
      traefik.frontend.rule: "Host: factory-api.wako057.net"
      traefik.docker.network: "front"
      traefik.port: 8080
      traefik.frontend.entryPoints: http
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
    networks:
      back:

  rabbitmq-orders:
    image: 'bitnami/rabbitmq:3.8'
    container_name: rabbitmq-orders
    expose:
      - 4369
      - 5672
      - 25672
      - 15672
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSWORD: "admin123"
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      back:
        aliases:
          - rabbitmq-orders.back.wako057.net

  bdd:
    container_name: bdd-postgres
    build: ${MINI_API_PATH:-.}/docker/postgres
    image: nexus.wako057.net:18442/bdd-postgres:1.0.0
    ports:
      - "5032:5432"
    volumes:
      - bdd-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      back:
        aliases:
          - dev-pgsql-01.dev.wako057.net
    labels:
      traefik.enable: false

volumes:
  bdd-postgres-data:
  rabbitmq_data:
    driver: local
